############ load datasets here using .RData ##############
load('data/data_summary.RData')
load('data/TMlist.RData')
load('data/NOTAntigen.RData')
load('data/cellline_mData.RData')
load('data/TumNormData.RData')
load('data/FetalAdrenalGland_FPKM_hg38_data.RData')
load('data/allDataPatient.RData')
load('data/Microarray_RMA_HumanGene1.0ST_29cells_genes.RData')
load('data/Microarray_RMA_U133Plus2_17cells_CCLE_genes.RData')
load('data/Microarray_RMA_U133Plus2_29cells_genes.RData')
load('data/Microarray_RMA_HumanWG6v2_38cells_genes.RData')
load('data/kallisto_TPM_41cells_genes.RData')
load('data/kallisto_TPM_8cells_modified_genes.RData')
load('data/STAR_FPKM_Target724_genes.RData')
load('data/kallisto_TPM_Target724_genes.RData')
load('data/STAR_FPKM_41cells_genes.RData')
load('data/STAR_FPKM_8cells_modified_genes.RData')
load('data/ExomeCalls85K8_10_13.RData')
load('data/ExomeCallsCCLE.RData')
load('data/compAim3_DE.RData')
load('data/compAim3_OE.RData')
load('data/compAim3_TM.RData')
load('data/Target724_targetcode.RData')
load('data/PDX_FPKM_hg38_data.RData')
load('data/PDX_FPKM_hg38_mData.RData')
load('data/ExomeCallsPDX.RData')
load('data/PDX_FPKM_hg38_nomm_data.RData')
load('data/PDX_FPKM_hg38_nomm_mData.RData')
############ load datasets here using .RData ##############


