############ load datasets here using .RData ##############
load('data/data_summary.RData')
load('data/TMlist.RData')
load('data/NOTAntigen.RData')
load('data/cellline_mData.RData')
load('data/TumNormData.RData')
load('data/FetalAdrenalGland_FPKM_hg38_data.RData')
load('data/allDataPatient.RData')
load('data/Microarray_RMA_HumanGene1.0ST_28cells_genes.RData')
load('data/Microarray_RMA_U133Plus2_17cells_CCLE_genes.RData')
load('data/Microarray_RMA_U133Plus2_29cells_genes.RData')
load('data/Microarray_RMA_HumanWG6v2_37cells_genes.RData')
load('data/kallisto_TPM_40cells_genes.RData')
load('data/kallisto_TPM_8cells_modified_genes.RData')
load('data/STAR_FPKM_Target723_genes.RData')
load('data/kallisto_TPM_Target723_genes.RData')
load('data/STAR_FPKM_40cells_genes.RData')
load('data/STAR_FPKM_8cells_modified_genes.RData')
load('data/ExomeCalls85K8_10_13.RData')
load('data/ExomeCallsCCLE.RData')
load('data/compAim3_DE.RData')
load('data/compAim3_OE.RData')
load('data/compAim3_TM.RData')
load('data/Target724_targetcode.RData')
load('data/ExomeCallsPDX.RData')
load('data/PDX_CellLines_Comparison.RData')
load('data/PPTC_FPKM_hg19_Wheeler_subtracted_data.RData')
load('data/PPTC_FPKM_hg19_Wheeler_subtracted_mData.RData')
load('data/PPTC_ExomeCalls.RData')
load('data/TARGET_MIRNA_FPKM_data.RData')
load('data/TARGET_MIRNA_FPKM_mData.RData')
load('data/PPTC_FPKM_hg38_Wheeler_subtracted_data.RData')
load('data/PPTC_FPKM_hg38_Wheeler_subtracted_mData.RData')
load('data/PPTC_TPM_hg19_Wheeler_data.RData')
load('data/PPTC_TPM_hg19_Wheeler_mData.RData')
############ load datasets here using .RData ##############


